### ISSUE TITLE
add gitlab CI example

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/terraform-training#37]
https://github.com/ondrejsika/gitlab-ci-training/blob/master/examples/library/terraform/terraform.gitlab-ci.yml

```yml
# .gitlab-ci.yml

include: https://raw.githubusercontent.com/ondrejsika/gitlab-ci-training/master/examples/library/terraform/terraform.gitlab-ci.yml

variables:
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/main
```
